apiVersion: apps/v1
kind: Deployment
metadata:
  name: simcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simcore
  template:
    metadata:
      labels:
        app: simcore
    spec:
      containers:
      - name: simcore
        image: <ECR_REGISTRY>/simcore:${IMAGE_TAG}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: config-volume
          mountPath: /app/traffic_simulation/core/config.json
          subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: simcore-service
spec:
  selector:
    app: simcore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
