apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizmodule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vizmodule
  template:
    metadata:
      labels:
        app: vizmodule
    spec:
      containers:
      - name: vizmodule
        image: <ECR_REGISTRY>/vizmodule:${IMAGE_TAG}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 8050
        volumeMounts:
        - name: config-volume
          mountPath: /app/traffic_simulation/core/config.json
          subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: vizmodule-service
spec:
  selector:
    app: vizmodule
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
  type: LoadBalancer  # adds an external IP address
